name: hello-world
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  say_hello:
    name: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: print my name
        run: echo "WWatsoi MCTHuy"

      - name: Grant execute permission
        run: chmod +x exercise-01-hello-world/my-time.sh

      - name: print my time
        run: exercise-01-hello-world/my-time.sh

      - name: print runner name
        run: echo "runner name is ${{runner.name}}"

      - name: Print runner OS
        run: echo "Runner OS is ${{ runner.os }}"

      - name: Print system information
        run: uname -a
